//! UDON Parser - Generated by genmachine
//!
//! This is a generated file. Do not edit directly.
//! Source: bootstrap.machine

use crate::event::Event;
use crate::span::Span;

/// Parser state for streaming UDON parsing.
///
/// The lifetime `'a` refers to the source buffer - all parsed content
/// is zero-copy slices into the original input.
pub struct Parser<'a> {
    input: &'a [u8],
    pos: usize,
    line: u32,
    column: u32,
    line_start: usize,

    /// Accumulator start position (for MARK/TERM pattern)
    mark_start: usize,

    /// Pending events to return
    events: Vec<Event<'a>>,
}

impl<'a> Parser<'a> {
    /// Create a new parser for the given input.
    #[inline]
    pub fn new(input: &'a [u8]) -> Self {
        Self {
            input,
            pos: 0,
            line: 1,
            column: 1,
            line_start: 0,
            mark_start: 0,
            events: Vec::new(),
        }
    }

    /// Parse the entire input and return all events.
    pub fn parse(&mut self) -> Vec<Event<'a>> {
        self.parse_line();
        std::mem::take(&mut self.events)
    }

    /// Check if we've reached end of input.
    #[inline]
    fn eof(&self) -> bool {
        self.pos >= self.input.len()
    }

    /// Get current byte without advancing.
    #[inline]
    fn peek(&self) -> Option<u8> {
        self.input.get(self.pos).copied()
    }

    /// Advance one byte (handles line/column tracking).
    #[inline]
    fn advance(&mut self) {
        if let Some(b) = self.input.get(self.pos) {
            if *b == b'\n' {
                self.line += 1;
                self.column = 1;
                self.pos += 1;
                self.line_start = self.pos;
            } else {
                self.column += 1;
                self.pos += 1;
            }
        }
    }

    /// Mark the current position for accumulation.
    #[inline]
    fn mark(&mut self) {
        self.mark_start = self.pos;
    }

    /// Get the accumulated slice from mark to current position.
    #[inline]
    fn term(&self) -> &'a [u8] {
        &self.input[self.mark_start..self.pos]
    }

    /// Create a span from mark to current position.
    #[inline]
    fn span_from_mark(&self) -> Span {
        Span::new(self.mark_start, self.pos)
    }

    /// Emit an event.
    #[inline]
    fn emit(&mut self, event: Event<'a>) {
        self.events.push(event);
    }

    // ========== Hand-written Helpers ==========

    /// Check if byte can start a LABEL (Unicode letter or underscore).
    /// LABEL = [\p{L}_][\p{L}\p{N}_-]*
    #[inline]
    fn is_label_start(&self, b: u8) -> bool {
        // Fast path for ASCII
        matches!(b, b'a'..=b'z' | b'A'..=b'Z' | b'_') ||
        // For non-ASCII, need to check Unicode - defer to full check
        (b >= 0x80 && self.is_unicode_letter_at(self.pos))
    }

    /// Check if byte can continue a LABEL.
    #[inline]
    fn is_label_continue(&self, b: u8) -> bool {
        matches!(b, b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'_' | b'-') ||
        (b >= 0x80 && self.is_unicode_letter_or_number_at(self.pos))
    }

    /// Check if position starts a Unicode letter (for non-ASCII).
    fn is_unicode_letter_at(&self, pos: usize) -> bool {
        // Decode UTF-8 and check if it's a Unicode letter
        if let Some(slice) = self.input.get(pos..) {
            if let Ok(s) = std::str::from_utf8(slice) {
                if let Some(c) = s.chars().next() {
                    return unicode_xid::UnicodeXID::is_xid_start(c);
                }
            }
        }
        false
    }

    /// Check if position is a Unicode letter or number (for non-ASCII).
    fn is_unicode_letter_or_number_at(&self, pos: usize) -> bool {
        if let Some(slice) = self.input.get(pos..) {
            if let Ok(s) = std::str::from_utf8(slice) {
                if let Some(c) = s.chars().next() {
                    return unicode_xid::UnicodeXID::is_xid_continue(c);
                }
            }
        }
        false
    }

    /// Scan a LABEL starting at current position.
    /// Returns the label slice and advances past it.
    fn scan_label(&mut self) -> Option<&'a [u8]> {
        let start = self.pos;

        // First char must be letter or underscore
        if let Some(&b) = self.input.get(self.pos) {
            if !self.is_label_start(b) {
                return None;
            }
            self.advance_bytes(self.char_len_at(self.pos));
        } else {
            return None;
        }

        // Continue with letters, numbers, underscore, hyphen
        while let Some(&b) = self.input.get(self.pos) {
            if self.is_label_continue(b) {
                self.advance_bytes(self.char_len_at(self.pos));
            } else {
                break;
            }
        }

        Some(&self.input[start..self.pos])
    }

    /// Get the byte length of the UTF-8 character at position.
    #[inline]
    fn char_len_at(&self, pos: usize) -> usize {
        match self.input.get(pos) {
            Some(&b) if b < 0x80 => 1,
            Some(&b) if b < 0xE0 => 2,
            Some(&b) if b < 0xF0 => 3,
            Some(&b) if b < 0xF8 => 4,
            _ => 1,
        }
    }

    /// Advance by a specific number of bytes.
    #[inline]
    fn advance_bytes(&mut self, n: usize) {
        for _ in 0..n {
            self.advance();
        }
    }

    /// Check if current position could start an element.
    /// Element starters: Unicode letter, '[', '.', '{', "'"
    #[inline]
    fn is_element_start(&self) -> bool {
        match self.peek() {
            Some(b'[') | Some(b'.') | Some(b'{') | Some(b'\'') => true,
            Some(b) => self.is_label_start(b),
            None => false,
        }
    }

    /// Check if a byte could start an element (for match guards).
    #[inline]
    fn is_element_start_byte(&self, b: u8) -> bool {
        matches!(b, b'[' | b'.' | b'{' | b'\'') || self.is_label_start(b)
    }

    /// Parse an element after seeing '|'.
    /// Handles: |name, |name[id], |name.class, |[id], |.class, etc.
    /// Returns true if an element was parsed, false if '|' should be prose.
    fn parse_element(&mut self) -> bool {
        // Check if this is actually an element
        if !self.is_element_start() {
            return false;
        }

        let start_pos = self.pos;

        // Parse element name (optional for anonymous elements)
        let name = if let Some(b) = self.peek() {
            if self.is_label_start(b) {
                self.scan_label()
            } else {
                None
            }
        } else {
            None
        };

        // TODO: Parse suffix after name (?, !, *, +)

        // Parse [id] if present
        let id = if self.peek() == Some(b'[') {
            self.advance(); // Skip [
            let id_start = self.pos;
            // Collect until ]
            while let Some(b) = self.peek() {
                if b == b']' {
                    break;
                }
                self.advance();
            }
            let id_slice = &self.input[id_start..self.pos];
            if self.peek() == Some(b']') {
                self.advance(); // Skip ]
            }
            if id_slice.is_empty() {
                None
            } else {
                Some(crate::Value::String(id_slice))
            }
        } else {
            None
        };

        // TODO: Parse suffix after id

        // Parse .class (multiple allowed)
        let mut classes = vec![];
        while self.peek() == Some(b'.') {
            self.advance(); // Skip .
            if let Some(class_name) = self.scan_label() {
                classes.push(class_name);
            }
        }

        // TODO: Parse suffix after classes

        self.emit(Event::ElementStart {
            name,
            id,
            classes,
            suffix: None,
            span: Span::new(start_pos, self.pos),
        });

        // Parse inline attributes (:key value)
        self.parse_inline_attributes();

        true
    }

    /// Parse inline attributes after element identity.
    /// Attributes: :key value :another-key another-value
    fn parse_inline_attributes(&mut self) {
        loop {
            // Skip whitespace
            while let Some(b' ') | Some(b'\t') = self.peek() {
                self.advance();
            }

            // Check for attribute
            if self.peek() != Some(b':') {
                break;
            }
            self.advance(); // Skip :

            // Parse attribute key
            let key = match self.scan_label() {
                Some(k) => k,
                None => break, // Invalid attribute
            };

            // Skip whitespace before value
            while let Some(b' ') | Some(b'\t') = self.peek() {
                self.advance();
            }

            // Check what follows
            let value = match self.peek() {
                None | Some(b'\n') | Some(b';') => None, // Flag attribute
                Some(b':') => None, // Next attribute (flag)
                Some(b'|') => None, // Inline element (flag)
                Some(b'"') => {
                    // Quoted string
                    self.advance(); // Skip opening quote
                    let start = self.pos;
                    while let Some(b) = self.peek() {
                        if b == b'"' {
                            break;
                        }
                        if b == b'\\' {
                            self.advance(); // Skip escape
                        }
                        self.advance();
                    }
                    let value_slice = &self.input[start..self.pos];
                    if self.peek() == Some(b'"') {
                        self.advance(); // Skip closing quote
                    }
                    Some(crate::Value::QuotedString(value_slice))
                }
                _ => {
                    // Unquoted value - collect until space, :, |, ;, or newline
                    let start = self.pos;
                    while let Some(b) = self.peek() {
                        match b {
                            b' ' | b'\t' | b':' | b'|' | b';' | b'\n' => break,
                            _ => self.advance(),
                        }
                    }
                    let value_slice = &self.input[start..self.pos];
                    if value_slice.is_empty() {
                        None
                    } else {
                        Some(crate::Value::String(value_slice))
                    }
                }
            };

            self.emit(Event::Attribute {
                key,
                value,
                span: Span::new(self.pos, self.pos), // TODO: proper span
            });
        }
    }

    /// Parse a complete element line after seeing '|' and confirming it's an element.
    /// This handles the element name, any content, and emits ElementEnd.
    fn parse_element_line(&mut self) {
        if self.parse_element() {
            self.parse_element_content();
            self.emit(Event::ElementEnd {
                span: Span::new(self.pos, self.pos),
            });
        }
    }

    /// Parse inline content after an element (until newline).
    /// Handles text and nested elements.
    fn parse_element_content(&mut self) {
        // Skip leading whitespace
        while let Some(b' ') | Some(b'\t') = self.peek() {
            self.advance();
        }

        // Check for content
        if self.eof() || self.peek() == Some(b'\n') {
            return;
        }

        // Collect text content
        self.mark();
        while let Some(b) = self.peek() {
            match b {
                b'\n' => break,
                b';' => break, // Comment starts
                b'|' => {
                    // Could be nested element - emit text so far
                    if self.pos > self.mark_start {
                        self.emit(Event::Text {
                            content: self.term(),
                            span: self.span_from_mark(),
                        });
                    }
                    self.advance(); // Skip |
                    if self.parse_element() {
                        self.parse_element_content();
                        // Emit ElementEnd for this nested element
                        self.emit(Event::ElementEnd {
                            span: Span::new(self.pos, self.pos),
                        });
                        // After nested element returns, continue collecting
                        self.mark();
                    } else {
                        // Not an element, continue as text
                        // But we already advanced past |, need to include it
                        // This is tricky - for now just continue
                    }
                }
                _ => self.advance(),
            }
        }

        // Emit remaining text
        if self.pos > self.mark_start {
            self.emit(Event::Text {
                content: self.term(),
                span: self.span_from_mark(),
            });
        }
    }

    // ========== Generated State Machine ==========


    fn parse_line(&mut self) {
        #[derive(Clone, Copy)]
        enum State { SMain, SEscaped, SAfterPipe, STextWithPipe, SText, SComment }

        let mut state = State::SMain;
        loop {
            if self.eof() {
                return;
            }

            match state {
                State::SMain => {
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.advance();
                            state = State::SMain;
                        }
                        b'\'' => {
                            self.advance();
                            state = State::SEscaped;
                        }
                        b';' => {
                            self.advance();
                            self.mark();
                            state = State::SComment;
                        }
                        b'|' => {
                            self.mark();
                            self.advance();
                            state = State::SAfterPipe;
                        }
                        _ => {
                            self.mark();
                            state = State::SText;
                        }
                    }
                }
                State::SEscaped => {
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.advance();
                            state = State::SMain;
                        }
                        b'\'' => {
                            self.mark();
                            self.advance();
                            state = State::SText;
                        }
                        _ => {
                            self.mark();
                            self.advance();
                            state = State::SText;
                        }
                    }
                }
                State::SAfterPipe => {
                    match self.peek().unwrap() {
                        b'\n' => {
                            state = State::STextWithPipe;
                        }
                        b' ' | b'\t' => {
                            state = State::STextWithPipe;
                        }
                        b'-' => {
                            state = State::STextWithPipe;
                        }
                        b'|' => {
                            state = State::STextWithPipe;
                        }
                        b if self.is_element_start_byte(b) => {
                            self.parse_element_line();
                            state = State::SMain;
                        }
                        _ => {
                            state = State::STextWithPipe;
                        }
                    }
                }
                State::STextWithPipe => {
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SMain;
                        }
                        b';' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            self.mark();
                            state = State::SComment;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SText => {
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SMain;
                        }
                        b';' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            self.mark();
                            state = State::SComment;
                        }
                        b'|' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SAfterPipe;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SComment => {
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SMain;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
            }
        }
    }

}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_empty_input() {
        let mut parser = Parser::new(b"");
        let events = parser.parse();
        assert!(events.is_empty());
    }

    #[test]
    fn test_comment() {
        let mut parser = Parser::new(b"; this is a comment\n");
        let events = parser.parse();
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], Event::Comment { .. }));
    }

    #[test]
    fn test_text() {
        let mut parser = Parser::new(b"hello world\n");
        let events = parser.parse();
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], Event::Text { .. }));
    }
}
