//! UDON Core Parser
//!
//! Streaming, event-based parser for UDON (Universal Document & Object Notation).
//! Generated by descent from the generator/NN-*.descent.udon grammar units.
//!
//! # Architecture
//!
//! - **parser.rs** - Generated recursive descent parser (callback-based)
//! - **tree.rs** - Tree/AST representation built from parser events
//! - **span.rs** - Span/Location types
//!
//! # Two APIs
//!
//! ## Streaming (SAX-like)
//!
//! ```
//! use udon_core::Parser;
//!
//! Parser::new(b"|div Hello\n").parse(|event| {
//!     println!("{}", event.format_line());
//! });
//! ```
//!
//! ## Tree (DOM-like)
//!
//! ```
//! use udon_core::tree::Document;
//!
//! let doc = Document::parse(b"|div Hello\n").unwrap();
//! for node in doc.root().children() {
//!     println!("{:?}", node.kind());
//! }
//! ```

/// The core-spec version this parser TARGETS (`spec/CORE-VERSION`). Targeting
/// is a declaration, not an achievement: compliance is proven only by passing
/// that version's fixture group (`core/fixtures/v<major.minor>/`). Last
/// version actually passed: **0.8.0** (tag `core-v0.8.0`, 2026-07-15).
pub const CORE_COMPLIANCE: &str = "0.9.0-alpha.2";

pub mod parser;
pub mod parser_pd;
pub mod span;
pub mod stream_tree;
pub mod tree;

pub use parser::*;
pub use parser_pd::PushdownParser;
pub use span::{Location, Span};
pub use stream_tree::{StreamingTreeParser, TreeStream};
pub use tree::{Document, Node, NodeKind, Value, Attribute, ElementView};
