//! UDON Core Parser
//!
//! Streaming, event-based parser for UDON (Universal Document & Object Notation).
//! Generated by descent from udon.desc.
//!
//! # Architecture
//!
//! - **parser.rs** - Generated recursive descent parser (callback-based)
//! - **tree.rs** - Tree/AST representation built from parser events
//! - **span.rs** - Span/Location types
//!
//! # Two APIs
//!
//! ## Streaming (SAX-like)
//!
//! ```
//! use udon_core::Parser;
//!
//! Parser::new(b"|div Hello\n").parse(|event| {
//!     println!("{}", event.format_line());
//! });
//! ```
//!
//! ## Tree (DOM-like)
//!
//! ```
//! use udon_core::tree::Document;
//!
//! let doc = Document::parse(b"|div Hello\n").unwrap();
//! for node in doc.root().children() {
//!     println!("{:?}", node.kind());
//! }
//! ```

pub mod parser;
pub mod span;
pub mod tree;

pub use parser::*;
pub use span::{Location, Span};
pub use tree::{Document, Node, NodeKind, Value, Attribute, ElementView};
